### PR TITLE
list-algorithms-patch

### PR DESCRIPTION
**Pull request by galbraic**
List of Algorithms page title should be centered and all caps, was previously left-aligned and standard capitalization

### CODE REVIEW

**Comment by lotten** [comment]
Thanks for the change! But I'm wondering, is it not the same as https://github.com/lotten/uci-thesis-latex/blob/824d8a9fc79968ab0ef7cc07cc3824f62aa757f3/thesis.tex#L49 ?

**Comment by galbraic** [comment]
Both accomplish the same thing, but I'm not sure that the current implementation is the best way to get it done. Shouldn't as much of the formatting as possible be done in ucithesis.cls (which is where the titles for the other list pages are formatted)? It is relatively easy to forget to uncomment that line, as I did (since I have a header with all the packages that I typically use that I copy & paste into new projects). Up to you if you want to leave it as-is or merge my change.

**Comment by lotten** [comment]
I'm trying to understand the difference better. I don't remember the latex semantics, but what happens if you have the \renewcommand in the cls without using the algorithm package later?

**Comment by galbraic** [comment]
it will still compile without warning. That block will only get executed if \listalgorithmname is defined, which is done by importing the algorithm package

**Comment by lotten** [comment]
Awesome, in that case I agree the cls is the better place for it. But can you then remove it from thesis.tex? Happy to merge after that!

**Comment by galbraic** [comment]
ok, that should do it

**Comment by lotten** [comment]
Great, thanks!

**Pull request merged**
